param(
    [string]$ProjectDir,
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "common.ps1")

if ([string]::IsNullOrWhiteSpace($ProjectDir)) {
    $ProjectDir = Get-AutoDLRepoRoot
}
if (-not (Test-Path $ProjectDir)) {
    throw "ProjectDir does not exist: $ProjectDir"
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $OutputPath = Join-Path (Join-Path (Get-AutoDLRepoRoot) "result") "3dgs-discovery-$stamp.ps1"
}

$outputDir = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

$readmeFiles = @(Get-ChildItem -Path $ProjectDir -File -Recurse -Include "README*", "readme*" -ErrorAction SilentlyContinue | Select-Object -First 8)
$envFiles = @(Get-ChildItem -Path $ProjectDir -File -Recurse -Include "environment.yml", "environment.yaml", "requirements.txt", "setup.py", "pyproject.toml", "setup.cfg" -ErrorAction SilentlyContinue | Select-Object -First 30)
$pythonFiles = @(Get-ChildItem -Path $ProjectDir -File -Recurse -Filter "*.py" -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch "[\\/](\.git|__pycache__|build|dist)[\\/]" })

function Find-RelativePath {
    param([System.IO.FileSystemInfo]$Item)
    $rootPath = (Resolve-Path $ProjectDir).Path.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    $itemPath = $Item.FullName
    if ($itemPath.StartsWith($rootPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $itemPath.Substring($rootPath.Length).TrimStart([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar).Replace("\", "/")
    }
    return $itemPath.Replace("\", "/")
}

$entryNames = @(
    "train.py", "render.py", "metrics.py", "eval.py", "evaluate.py", "test.py", "main.py",
    "train_*.py", "*_train.py", "render_*.py", "*_render.py", "metric*.py"
)
$entryFiles = New-Object System.Collections.Generic.List[string]
foreach ($pattern in $entryNames) {
    foreach ($file in @(Get-ChildItem -Path $ProjectDir -File -Recurse -Filter $pattern -ErrorAction SilentlyContinue)) {
        $rel = Find-RelativePath $file
        if (-not $entryFiles.Contains($rel)) {
            $entryFiles.Add($rel)
        }
    }
}

$readmeText = ""
foreach ($readme in $readmeFiles) {
    try {
        $readmeText += "`n--- $((Find-RelativePath $readme)) ---`n"
        $readmeText += (Get-Content -Path $readme.FullName -Raw -ErrorAction Stop)
    } catch {
    }
}

$commandLines = New-Object System.Collections.Generic.List[string]
foreach ($line in ($readmeText -split "`r?`n")) {
    $trimmed = $line.Trim()
    if ($trimmed -match "^(python|python3|CUDA_VISIBLE_DEVICES=|conda|pip|bash|sh)\b" -or $trimmed -match "python\s+[^`\s]+\.py") {
        $cleaned = $trimmed.TrimStart('`').Trim()
        if ($cleaned.Length -gt 0 -and -not $commandLines.Contains($cleaned)) {
            $commandLines.Add($cleaned)
        }
    }
}

$trainEntry = ($entryFiles | Where-Object { $_ -match "(^|/)train[^/]*\.py$|(^|/)[^/]*_train\.py$" } | Select-Object -First 1)
$renderEntry = ($entryFiles | Where-Object { $_ -match "(^|/)render[^/]*\.py$|(^|/)[^/]*_render\.py$" } | Select-Object -First 1)
$evalEntry = ($entryFiles | Where-Object { $_ -match "(^|/)(metrics?|eval|evaluate)[^/]*\.py$" } | Select-Object -First 1)

if ([string]::IsNullOrWhiteSpace($trainEntry)) { $trainEntry = "train.py" }
if ([string]::IsNullOrWhiteSpace($renderEntry)) { $renderEntry = "render.py" }
if ([string]::IsNullOrWhiteSpace($evalEntry)) { $evalEntry = "metrics.py" }

$setupCommands = New-Object System.Collections.Generic.List[string]
$setupCommands.Add("git submodule update --init --recursive")
if (Test-Path (Join-Path $ProjectDir "environment.yml")) {
    $setupCommands.Add("conda env update -n `$AutoDL3DGSRemoteCondaEnv -f environment.yml")
} elseif (Test-Path (Join-Path $ProjectDir "environment.yaml")) {
    $setupCommands.Add("conda env update -n `$AutoDL3DGSRemoteCondaEnv -f environment.yaml")
}
$setupCommands.Add("python -m pip install --upgrade pip setuptools wheel")
if (Test-Path (Join-Path $ProjectDir "requirements.txt")) {
    $setupCommands.Add("python -m pip install -r requirements.txt")
}
if (Test-Path (Join-Path $ProjectDir "setup.py")) {
    $setupCommands.Add("python -m pip install -e .")
}
$setupCommands.Add("if [ -d submodules/diff-gaussian-rasterization ]; then python -m pip install submodules/diff-gaussian-rasterization; fi")
$setupCommands.Add("if [ -d submodules/simple-knn ]; then python -m pip install submodules/simple-knn; fi")

$content = New-Object System.Collections.Generic.List[string]
$content.Add("# Generated by discover_3dgs_project.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$content.Add("# Review before copying into scripts/autodl/autodl.3dgs.config.ps1.")
$content.Add("")
$content.Add("# Detected README files:")
foreach ($file in $readmeFiles) { $content.Add("# - $(Find-RelativePath $file)") }
$content.Add("# Detected dependency/environment files:")
foreach ($file in $envFiles) { $content.Add("# - $(Find-RelativePath $file)") }
$content.Add("# Detected likely entry files:")
foreach ($file in $entryFiles) { $content.Add("# - $file") }
$content.Add("")
$content.Add("`$AutoDL3DGSSetupCommands = @(")
for ($i = 0; $i -lt $setupCommands.Count; $i++) {
    $comma = if ($i -lt $setupCommands.Count - 1) { "," } else { "" }
    $escaped = $setupCommands[$i].Replace('"', '`"')
    $content.Add("    `"$escaped`"$comma")
}
$content.Add(")")
$content.Add("")
$content.Add("`$AutoDL3DGSTrainCommand = `"python $trainEntry -s `$AutoDL3DGSRemoteSceneDir -m `$AutoDL3DGSRemoteModelDir --iterations 30000`"")
$content.Add("`$AutoDL3DGSRenderCommand = `"python $renderEntry -m `$AutoDL3DGSRemoteModelDir`"")
$content.Add("`$AutoDL3DGSEvalCommand = `"python $evalEntry -m `$AutoDL3DGSRemoteModelDir`"")
$content.Add("")
$content.Add("# README command candidates:")
foreach ($cmd in $commandLines | Select-Object -First 40) {
    $content.Add("# $cmd")
}

[System.IO.File]::WriteAllLines($OutputPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "3DGS discovery complete."
Write-Host "Project dir: $ProjectDir"
Write-Host "Suggested profile: $OutputPath"
Write-Host "Detected entry files: $($entryFiles.Count)"
Write-Host "README command candidates: $($commandLines.Count)"
